### PR TITLE
Fix BC break for breadcrumbs namespace

### PR DESCRIPTION
**Pull request by bocharsky-bw**

### CODE REVIEW

**Comment by bocharsky-bw** [comment]
Fix BC break for #46

**Comment by bocharsky-bw** [comment]
@richsage ping

**Comment by bocharsky-bw** [comment]
@richsage What do you think? Could we merge it?

**Comment by richsage** [comment]
Yes - I think this should be fine. I have some reservations about adding parameters to methods defined as `void` (such as `rewind()` and similar)) but for now let's go with it :)

**Pull request merged**
