### PR TITLE
Allow Symfony 3

### PR DESCRIPTION
**Pull request by Soullivaneuh**

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
BTW, it would be great to setup Travis and run tests with several Symfony and PHP versions.

**Comment by richsage** [comment]
It would be good to have some actual tests to be able to run on Travis! But thanks :-)

**Comment by Soullivaneuh** [comment]
Thanks, could we have a new tag for it?

**Comment by richsage** [comment]
@Soullivaneuh done, 1.2.1

**Comment by Soullivaneuh** [comment]
Thanks! :+1:

**Pull request merged**
