### PR TITLE
Namespace crumbs

### PR DESCRIPTION
**Pull request by richsage**
This allows namespacing of breadcrumbs - to allow for eg "Main" breadcrumbs and "Sub-navigation" breadcrumbs. Big thanks to @bocharsky-bw :-)

### CODE REVIEW

**Comment by bocharsky-bw** [comment]
When could we merge it to the `master`?

**Comment by richsage** [comment]
I'm wondering if it would be good to have some tests with it - but that might be a separate thing altogether, given that there aren't any currently... :-)

**Comment by bocharsky-bw** [comment]
I think tests will be great! I plan to add some unit tests but a bit later...

**Comment by richsage** [comment]
yep that's fair :-) OK, I'll merge and release?

**Comment by bocharsky-bw** [comment]
Yes, please )

**Pull request merged**
