### PR TITLE
Unordered to ordered list

### PR DESCRIPTION
**Pull request by Simounet**
Hi,
A breadcrumb is by definition an ordered list so it would be better with an ol tag.

Have a nice day and thanks for this great bundle.

### CODE REVIEW

**Comment by bocharsky-bw** [comment]
@Simounet Seems quite reasonable to me at first sight! I just wondering, do you have any proofs of this changes with a link to some standard?

**Comment by Simounet** [comment]
Look at the [schema.org Breadcrumb List](https://schema.org/BreadcrumbList). It is not a W3C recommendation but it is often named as a reference.

**Comment by bocharsky-bw** [comment]
:+1:

BTW, should we also remove `itemscope` and `itemtype` attributes from list items? Seems it outdated, isn't it? What do you think?

**Comment by Simounet** [comment]
The data-vocabulary.org schema is outdated but `itemscope` and `itemtype` are not. I can change this to be up to date if you want.

**Comment by bocharsky-bw** [comment]
Wow, it'll be very cool! But you should do this changes in other PR I think.

**Comment by bocharsky-bw** [comment]
@Simounet Ah, never mind!

**Comment by Simounet** [comment]
Tell me what do you prefer. I can open a new PR, it's not a big deal. :)

**Comment by bocharsky-bw** [comment]
The best way is open new PR :)

**Comment by Simounet** [comment]
Ok, so be it. Do you prefer that I wait for you to merge this first one, avoiding you the post merge of `ul` to `ol` change?

**Comment by bocharsky-bw** [comment]
Yea, let's wait for merge first...

@richsage I think we could merge this minor changes.

**Comment by richsage** [comment]
Yep - this looks good, thanks :)

**Pull request merged**
