### PR TITLE
Fix deprecation for symfony/config 4.2

### PR DESCRIPTION
**Pull request by mhujer**

### CODE REVIEW

**Comment by mhujer** [comment]
Build failure seems unrelated as it fails during install

**Comment by sampart** [comment]
Thanks for contributing, @mhujer, that's great.  Do you need a release made for this?

**Comment by mhujer** [comment]
@sampart Thanks for merging! Yes, it would be nice to have a release with this fix, because everyone using this library with Symfony 4.2 will be getting deprecation warnings.

**Comment by sampart** [comment]
Sounds like a plan.  Here you go: https://github.com/whiteoctober/BreadcrumbsBundle/releases/tag/1.4.3

**Comment by mhujer** [comment]
Awesome 👍

**Pull request merged**
