### PR TITLE
Drop data-vocabulary.org outdated schema for schema.org

### PR DESCRIPTION
**Pull request by Simounet**
Hi,
We are now using the [breadcrumb list's schema of schema.org](http://schema.org/BreadcrumbList).

Have a nice day.

### CODE REVIEW

**Comment by richsage** [comment]
Looks good - thanks! :)

**Comment by Simounet** [comment]
You're welcome.

**Comment by Simounet** [comment]
Can you tag it as 1.2.2 please?

**Comment by richsage** [comment]
whoops - missed that, sorry. Have just tagged 1.2.2 :)

**Comment by Simounet** [comment]
No problem. Thanks.

**Pull request merged**
